-- Coach OS — 200 Global Exercises Seed (production)
-- Run manually: psql -d <database> -f seed-exercises.sql
-- All exercises are global (tenant_id IS NULL)
-- muscleGroup values match MuscleGroup enum
-- media_url populated from ExerciseDB API GIFs via S3

INSERT INTO exercises (id, name, description, muscle_group, instructions, media_url, tenant_id, created_at, updated_at) VALUES


-- ============================================================
-- PEITORAL (20 exercises)
-- ============================================================
(gen_random_uuid(), 'Supino Reto com Barra', 'Exercício composto para peitoral com barra no banco reto.', 'peitoral', 'Deite no banco reto, segure a barra na largura dos ombros, desça até o peito e empurre para cima.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/supino-reto-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Supino Inclinado com Barra', 'Supino no banco inclinado para enfatizar a parte superior do peitoral.', 'peitoral', 'Ajuste o banco a 30-45 graus, segure a barra e execute o movimento controlado.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/supino-inclinado-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Supino Declinado com Barra', 'Supino no banco declinado para enfatizar a parte inferior do peitoral.', 'peitoral', 'Ajuste o banco em declínio, desça a barra até a parte inferior do peito e empurre.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/supino-declinado-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Supino Reto com Halteres', 'Supino reto utilizando halteres para maior amplitude de movimento.', 'peitoral', 'Deite no banco reto, segure os halteres e execute o movimento de pressão.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/supino-reto-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Supino Inclinado com Halteres', 'Supino inclinado com halteres para peitoral superior.', 'peitoral', 'No banco inclinado, pressione os halteres para cima com movimento controlado.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/supino-inclinado-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Supino Declinado com Halteres', 'Supino declinado com halteres para peitoral inferior.', 'peitoral', 'No banco declinado, pressione os halteres para cima controladamente.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/supino-declinado-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Crucifixo com Halteres', 'Exercício de isolamento para peitoral no banco reto.', 'peitoral', 'Deite no banco, abra os braços com os halteres em arco e retorne à posição inicial.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/crucifixo-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Crucifixo Inclinado com Halteres', 'Crucifixo no banco inclinado para peitoral superior.', 'peitoral', 'No banco inclinado, execute o movimento de abertura com os halteres.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/crucifixo-inclinado-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Flexão de Braço', 'Exercício com peso corporal para peitoral, ombros e tríceps.', 'peitoral', 'Em posição de prancha, desça o corpo até o peito quase tocar o chão e empurre para cima.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/flexao-de-braco.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Flexão de Braço Diamante', 'Flexão com mãos juntas para enfatizar tríceps e peitoral interno.', 'peitoral', 'Posicione as mãos formando um diamante abaixo do peito e execute a flexão.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/flexao-de-braco-diamante.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Flexão de Braço com Pés Elevados', 'Flexão com os pés em um banco para aumentar a intensidade.', 'peitoral', 'Apoie os pés em um banco elevado e execute a flexão normalmente.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/flexao-de-braco-com-pes-elevados.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Cross Over no Cabo', 'Exercício de isolamento para peitoral usando cabos.', 'peitoral', 'Em pé entre os cabos, puxe as mãos para frente e para baixo em movimento de abraço.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/cross-over-no-cabo.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Peck Deck (Voador)', 'Máquina de isolamento para peitoral.', 'peitoral', 'Sentado na máquina, junte os braços à frente do peito de forma controlada.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/peck-deck-voador.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Supino na Máquina (Chest Press)', 'Supino guiado na máquina.', 'peitoral', 'Sentado na máquina, empurre os pegadores para frente e retorne controladamente.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/supino-na-maquina-chest-press.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Pullover com Halter', 'Exercício para peitoral e costas com halter no banco reto.', 'peitoral', 'Deite no banco, segure o halter acima do peito e leve atrás da cabeça em arco.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/pullover-com-halter.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Flexão de Braço Aberta', 'Flexão com mãos mais afastadas para maior ativação do peitoral.', 'peitoral', 'Posicione as mãos mais abertas que a largura dos ombros e execute a flexão.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/flexao-de-braco-aberta.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Chest Press Inclinado na Máquina', 'Supino inclinado na máquina para peitoral superior.', 'peitoral', 'Sentado na máquina inclinada, empurre para frente controladamente.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/chest-press-inclinado-na-maquina.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Cross Over Baixo (Low Cable Fly)', 'Cross over com cabos baixos para peitoral superior.', 'peitoral', 'Puxe os cabos de baixo para cima em movimento de abraço.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/cross-over-baixo-low-cable-fly.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Supino Reto no Smith', 'Supino guiado na máquina Smith.', 'peitoral', 'No Smith, execute o supino reto de forma guiada e controlada.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/supino-reto-no-smith.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Crucifixo no Cabo (Cable Fly)', 'Crucifixo com cabos cruzados na altura do peito.', 'peitoral', 'Com cabos na altura do peito, junte as mãos à frente em movimento de abraço.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/crucifixo-no-cabo-cable-fly.gif', NULL, NOW(), NOW()),

-- ============================================================
-- COSTAS (21 exercises)
-- ============================================================
(gen_random_uuid(), 'Puxada na Barra Fixa (Pull-up)', 'Exercício com peso corporal para costas e bíceps.', 'costas', 'Pendure-se na barra com pegada pronada e puxe o corpo até o queixo passar da barra.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/puxada-na-barra-fixa-pull-up.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Puxada na Barra Fixa Supinada (Chin-up)', 'Barra fixa com pegada supinada, mais ênfase em bíceps.', 'costas', 'Pendure-se com as palmas voltadas para você e puxe o corpo para cima.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/puxada-na-barra-fixa-supinada-chin-up.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Puxada no Pulley Frontal', 'Puxada no cabo para costas com barra frontal.', 'costas', 'Sentado, puxe a barra até a altura do peito mantendo as costas retas.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/puxada-no-pulley-frontal.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Puxada no Pulley Triângulo', 'Puxada com pegada neutra no triângulo.', 'costas', 'Sentado, puxe o triângulo até o peito com cotovelos rentes ao corpo.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/puxada-no-pulley-triangulo.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Remada Curvada com Barra', 'Exercício composto para costas com barra.', 'costas', 'Incline o tronco a 45 graus, puxe a barra até o abdômen e retorne.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/remada-curvada-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Remada Curvada com Barra Supinada', 'Remada curvada com pegada supinada para dorsais e bíceps.', 'costas', 'Incline o tronco, puxe a barra com pegada supinada até o abdômen.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/remada-curvada-com-barra-supinada.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Remada Unilateral com Halter', 'Remada com um halter apoiado no banco.', 'costas', 'Apoie um joelho e mão no banco, puxe o halter com o outro braço até a cintura.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/remada-unilateral-com-halter.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Remada Cavalinho (T-Bar Row)', 'Remada com barra fixa no chão em formato T.', 'costas', 'Posicione-se sobre a barra, puxe a carga até o peito com tronco inclinado.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/remada-cavalinho-t-bar-row.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Remada Sentado no Cabo (Seated Row)', 'Remada sentado com cabo para costas.', 'costas', 'Sentado, puxe a barra ou triângulo até o abdômen mantendo as costas retas.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/remada-sentado-no-cabo-seated-row.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Remada na Máquina', 'Remada guiada na máquina para costas.', 'costas', 'Sentado na máquina, puxe os pegadores até o abdômen controladamente.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/remada-na-maquina.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Pullover no Cabo', 'Pullover no cabo para dorsal.', 'costas', 'Em pé, segure a barra do cabo alto e puxe para baixo até a coxa com braços estendidos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/pullover-no-cabo.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Puxada Aberta no Pulley', 'Puxada com pegada ampla para latíssimo do dorso.', 'costas', 'Sentado, puxe a barra larga até o peito com cotovelos apontando para baixo.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/puxada-aberta-no-pulley.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Levantamento Terra', 'Exercício composto para cadeia posterior completa.', 'costas', 'Com barra no chão, agache, segure a barra e levante estendendo quadril e joelhos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/levantamento-terra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Remada Alta com Barra', 'Puxada vertical para costas superiores e ombros.', 'costas', 'Segure a barra com pegada estreita e puxe até a altura do queixo.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/remada-alta-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Remada no Smith', 'Remada curvada no Smith para movimento guiado.', 'costas', 'No Smith, incline o tronco e execute a remada de forma controlada.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/remada-no-smith.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Puxada Unilateral no Cabo', 'Puxada com um braço no cabo para costas.', 'costas', 'Em pé ou ajoelhado, puxe o cabo com um braço até a cintura.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/puxada-unilateral-no-cabo.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Remada Pendlay', 'Remada explosiva com a barra partindo do chão.', 'costas', 'Inicie cada repetição com a barra no chão, puxe explosivamente até o abdômen.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/remada-pendlay.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Good Morning', 'Exercício para lombar e cadeia posterior.', 'costas', 'Com a barra nas costas, incline o tronco para frente mantendo as costas retas.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/good-morning.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Hiperextensão (Back Extension)', 'Exercício para fortalecimento da lombar.', 'costas', 'No banco romano, desça o tronco e retorne à posição inicial contraindo a lombar.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/hiperextensao-back-extension.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Remada Gorilla', 'Remada alternada com halteres em posição de agachamento.', 'costas', 'Em posição de agachamento com dois halteres, puxe alternadamente até a cintura.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/remada-gorilla.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Puxada no Pulley com Barra V', 'Puxada com barra V para costas.', 'costas', 'Sentado, puxe a barra V até o peito com pegada neutra.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/puxada-no-pulley-com-barra-v.gif', NULL, NOW(), NOW()),

-- ============================================================
-- OMBROS (18 exercises)
-- ============================================================
(gen_random_uuid(), 'Desenvolvimento com Halteres', 'Exercício composto para ombros com halteres.', 'ombros', 'Sentado ou em pé, pressione os halteres acima da cabeça e retorne.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/desenvolvimento-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Desenvolvimento com Barra', 'Desenvolvimento frontal com barra para ombros.', 'ombros', 'Sentado, pressione a barra acima da cabeça partindo da altura dos ombros.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/desenvolvimento-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Desenvolvimento Arnold', 'Variação do desenvolvimento com rotação dos halteres.', 'ombros', 'Inicie com halteres na frente do rosto, rotacione e pressione acima da cabeça.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/desenvolvimento-arnold.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Elevação Lateral com Halteres', 'Isolamento para deltóide lateral.', 'ombros', 'Em pé, eleve os halteres lateralmente até a altura dos ombros.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/elevacao-lateral-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Elevação Lateral no Cabo', 'Elevação lateral usando cabo para tensão constante.', 'ombros', 'Com o cabo na lateral, eleve o braço lateralmente até a altura do ombro.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/elevacao-lateral-no-cabo.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Elevação Frontal com Halteres', 'Isolamento para deltóide anterior.', 'ombros', 'Em pé, eleve os halteres à frente até a altura dos ombros.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/elevacao-frontal-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Elevação Frontal com Barra', 'Elevação frontal com barra para deltóide anterior.', 'ombros', 'Segure a barra e eleve à frente até a altura dos ombros.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/elevacao-frontal-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Crucifixo Inverso com Halteres', 'Exercício para deltóide posterior.', 'ombros', 'Incline o tronco e abra os braços lateralmente com os halteres.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/crucifixo-inverso-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Crucifixo Inverso no Peck Deck', 'Deltóide posterior na máquina peck deck invertida.', 'ombros', 'Sentado de frente para a máquina, abra os braços para trás.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/crucifixo-inverso-no-peck-deck.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Face Pull no Cabo', 'Exercício para deltóide posterior e rotadores.', 'ombros', 'Puxe a corda do cabo alto em direção ao rosto com cotovelos altos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/face-pull-no-cabo.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Desenvolvimento na Máquina (Shoulder Press)', 'Desenvolvimento guiado na máquina.', 'ombros', 'Sentado na máquina, empurre os pegadores acima da cabeça.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/desenvolvimento-na-maquina-shoulder-press.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Elevação Lateral na Máquina', 'Elevação lateral na máquina para deltóide lateral.', 'ombros', 'Sentado na máquina, eleve os braços lateralmente de forma controlada.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/elevacao-lateral-na-maquina.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Remada Alta com Halteres', 'Puxada vertical com halteres para ombros e trapézio.', 'ombros', 'Segure os halteres e puxe para cima até a altura do queixo.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/remada-alta-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Desenvolvimento com Kettlebell', 'Desenvolvimento unilateral com kettlebell.', 'ombros', 'Segure o kettlebell na posição de rack e pressione acima da cabeça.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/desenvolvimento-com-kettlebell.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Elevação Lateral Inclinado', 'Elevação lateral deitado de lado no banco inclinado.', 'ombros', 'Deitado de lado no banco inclinado, eleve o halter lateralmente.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/elevacao-lateral-inclinado.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Y Raise com Halteres', 'Elevação em formato Y para deltóide e trapézio inferior.', 'ombros', 'Incline o tronco e eleve os halteres em ângulo de Y acima da cabeça.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/y-raise-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Desenvolvimento no Smith', 'Desenvolvimento na máquina Smith para ombros.', 'ombros', 'Sentado no Smith, pressione a barra acima da cabeça de forma guiada.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/desenvolvimento-no-smith.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Elevação Frontal com Disco', 'Elevação frontal segurando um disco de peso.', 'ombros', 'Segure o disco com ambas as mãos e eleve à frente até a altura dos ombros.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/elevacao-frontal-com-disco.gif', NULL, NOW(), NOW()),

-- ============================================================
-- BÍCEPS (17 exercises)
-- ============================================================
(gen_random_uuid(), 'Rosca Direta com Barra', 'Exercício básico para bíceps com barra reta.', 'bíceps', 'Em pé, segure a barra com pegada supinada e flexione os cotovelos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-direta-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca Direta com Barra W', 'Rosca com barra W para menor estresse no punho.', 'bíceps', 'Segure a barra W nas angulações e flexione os cotovelos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-direta-com-barra-w.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca Alternada com Halteres', 'Rosca alternada para bíceps com halteres.', 'bíceps', 'Em pé, flexione um braço de cada vez alternando os lados.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-alternada-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca Simultânea com Halteres', 'Rosca com ambos os halteres ao mesmo tempo.', 'bíceps', 'Em pé, flexione ambos os braços simultaneamente com halteres.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-simultanea-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca Martelo', 'Rosca com pegada neutra para bíceps e braquial.', 'bíceps', 'Segure os halteres com pegada neutra (palmas para dentro) e flexione.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-martelo.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca Concentrada', 'Rosca de isolamento sentado com halter.', 'bíceps', 'Sentado, apoie o cotovelo na parte interna da coxa e flexione o halter.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-concentrada.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca Scott com Barra W', 'Rosca no banco Scott para isolamento do bíceps.', 'bíceps', 'No banco Scott, flexione a barra W de forma controlada.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-scott-com-barra-w.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca Scott com Halter', 'Rosca unilateral no banco Scott.', 'bíceps', 'Apoie o braço no banco Scott e flexione o halter.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-scott-com-halter.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca no Cabo (Pulley)', 'Rosca direta usando cabo para tensão constante.', 'bíceps', 'Em pé frente ao cabo baixo, flexione os braços puxando a barra.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-no-cabo-pulley.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca Martelo no Cabo (Rope Curl)', 'Rosca com corda no cabo para bíceps e braquial.', 'bíceps', 'Puxe a corda do cabo baixo com pegada neutra flexionando os cotovelos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-martelo-no-cabo-rope-curl.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca Inclinada com Halteres', 'Rosca no banco inclinado para maior alongamento do bíceps.', 'bíceps', 'Deitado no banco inclinado, flexione os halteres com braços pendurados.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-inclinada-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca 21', 'Rosca com 3 fases de 7 repetições cada.', 'bíceps', '7 reps na metade inferior, 7 na metade superior, 7 completas.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-21.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca Spider', 'Rosca no lado inclinado do banco Scott.', 'bíceps', 'Apoie o peito no lado inclinado do banco e flexione os halteres.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-spider.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca Inversa com Barra', 'Rosca com pegada pronada para braquiorradial.', 'bíceps', 'Segure a barra com pegada pronada e flexione os cotovelos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-inversa-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca no Cross Over', 'Rosca bilateral nos cabos altos.', 'bíceps', 'Com cabos altos, flexione os braços em direção à cabeça.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-no-cross-over.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca Martelo Alternada', 'Rosca martelo alternando os braços.', 'bíceps', 'Alterne os braços na rosca com pegada neutra.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-martelo-alternada.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca Concentrada no Cabo', 'Rosca concentrada unilateral no cabo.', 'bíceps', 'Sentado, puxe o cabo baixo com um braço apoiado na coxa.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-concentrada-no-cabo.gif', NULL, NOW(), NOW()),

-- ============================================================
-- TRÍCEPS (17 exercises)
-- ============================================================
(gen_random_uuid(), 'Tríceps Pulley com Barra', 'Extensão de tríceps no cabo com barra reta.', 'tríceps', 'Em pé, empurre a barra do cabo para baixo estendendo os cotovelos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/triceps-pulley-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Tríceps Pulley com Corda', 'Extensão de tríceps com corda no cabo.', 'tríceps', 'Empurre a corda para baixo e abra as pontas no final do movimento.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/triceps-pulley-com-corda.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Tríceps Testa com Barra W', 'Extensão de tríceps deitado com barra W.', 'tríceps', 'Deitado no banco, desça a barra até a testa e estenda os braços.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/triceps-testa-com-barra-w.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Tríceps Testa com Halteres', 'Extensão de tríceps deitado com halteres.', 'tríceps', 'Deitado, desça os halteres até a testa e estenda os braços.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/triceps-testa-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Tríceps Francês com Halter', 'Extensão de tríceps acima da cabeça com halter.', 'tríceps', 'Sentado ou em pé, estenda o halter acima da cabeça com ambas as mãos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/triceps-frances-com-halter.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Tríceps Francês com Barra W', 'Extensão acima da cabeça com barra W.', 'tríceps', 'Sentado, desça a barra atrás da cabeça e estenda os braços.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/triceps-frances-com-barra-w.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Tríceps Coice (Kickback)', 'Extensão de tríceps unilateral inclinado.', 'tríceps', 'Incline o tronco, mantenha o cotovelo fixo e estenda o braço para trás.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/triceps-coice-kickback.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Mergulho no Banco', 'Tríceps no banco com peso corporal.', 'tríceps', 'Apoie as mãos no banco atrás de você, desça o corpo flexionando os cotovelos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/mergulho-no-banco.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Mergulho nas Paralelas', 'Exercício composto para tríceps e peitoral inferior.', 'tríceps', 'Nas paralelas, desça o corpo e empurre para cima focando no tríceps.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/mergulho-nas-paralelas.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Tríceps Pulley Inverso', 'Extensão no cabo com pegada supinada.', 'tríceps', 'Empurre a barra para baixo com pegada supinada para cabeça medial.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/triceps-pulley-inverso.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Tríceps no Cross Over (Overhead)', 'Extensão de tríceps no cabo acima da cabeça.', 'tríceps', 'De costas para o cabo, estenda a corda acima da cabeça.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/triceps-no-cross-over-overhead.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Supino Fechado com Barra', 'Supino com pegada fechada para tríceps.', 'tríceps', 'No banco reto, segure a barra com pegada fechada e execute o supino.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/supino-fechado-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Tríceps na Máquina', 'Extensão de tríceps na máquina guiada.', 'tríceps', 'Sentado na máquina, empurre os pegadores para baixo estendendo os cotovelos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/triceps-na-maquina.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Flexão de Braço Fechada', 'Flexão com mãos na largura dos ombros para tríceps.', 'tríceps', 'Execute a flexão com as mãos na largura dos ombros, cotovelos rentes ao corpo.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/flexao-de-braco-fechada.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Tríceps Unilateral no Cabo', 'Extensão unilateral no cabo para tríceps.', 'tríceps', 'Com um braço, empurre o cabo para baixo estendendo o cotovelo.', NULL, NULL, NOW(), NOW()),
(gen_random_uuid(), 'Tríceps Testa no Cabo', 'Extensão no banco usando cabo baixo.', 'tríceps', 'Deitado no banco com cabo baixo, execute a extensão de tríceps testa.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/triceps-testa-no-cabo.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Tríceps Mergulho Assistido na Máquina', 'Mergulho com assistência na máquina.', 'tríceps', 'Na máquina assistida, execute o mergulho com apoio de peso.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/triceps-mergulho-assistido-na-maquina.gif', NULL, NOW(), NOW()),

-- ============================================================
-- PERNAS (28 exercises)
-- ============================================================
(gen_random_uuid(), 'Agachamento Livre com Barra', 'Exercício composto principal para pernas.', 'pernas', 'Com a barra nas costas, agache até as coxas ficarem paralelas ao chão e suba.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/agachamento-livre-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Agachamento Frontal', 'Agachamento com a barra na frente dos ombros.', 'pernas', 'Segure a barra na frente dos ombros e agache mantendo o tronco ereto.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/agachamento-frontal.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Agachamento Goblet', 'Agachamento segurando um halter ou kettlebell no peito.', 'pernas', 'Segure o peso próximo ao peito e agache profundamente.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/agachamento-goblet.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Agachamento no Smith', 'Agachamento guiado na máquina Smith.', 'pernas', 'No Smith, posicione a barra nas costas e agache de forma guiada.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/agachamento-no-smith.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Agachamento Búlgaro', 'Agachamento unilateral com pé traseiro elevado.', 'pernas', 'Apoie o pé traseiro no banco e agache com a perna da frente.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/agachamento-bulgaro.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Agachamento Sumô', 'Agachamento com pernas afastadas e pés apontados para fora.', 'pernas', 'Com pernas afastadas e pés virados para fora, agache segurando o peso.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/agachamento-sumo.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Leg Press 45°', 'Exercício na máquina para quadríceps e glúteos.', 'pernas', 'Na máquina a 45 graus, empurre a plataforma e retorne controladamente.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/leg-press-45.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Leg Press Horizontal', 'Leg press na máquina horizontal.', 'pernas', 'Sentado na máquina horizontal, empurre a plataforma com os pés.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/leg-press-horizontal.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Hack Squat', 'Agachamento na máquina hack.', 'pernas', 'Na máquina hack, agache de forma guiada com apoio nas costas.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/hack-squat.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Cadeira Extensora', 'Isolamento de quadríceps na máquina.', 'pernas', 'Sentado, estenda as pernas levantando a caneleira.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/cadeira-extensora.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Mesa Flexora', 'Isolamento de isquiotibiais na máquina.', 'pernas', 'Deitado de bruços, flexione as pernas puxando a caneleira.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/mesa-flexora.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Cadeira Flexora', 'Flexão de pernas sentado na máquina.', 'pernas', 'Sentado na máquina, flexione as pernas puxando a caneleira para trás.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/cadeira-flexora.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Stiff com Barra', 'Exercício para isquiotibiais e glúteos.', 'pernas', 'Com as pernas semi-estendidas, incline o tronco para frente com a barra.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/stiff-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Stiff com Halteres', 'Stiff utilizando halteres.', 'pernas', 'Segure os halteres e incline o tronco mantendo as pernas semi-estendidas.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/stiff-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Stiff Unilateral', 'Stiff com uma perna só para equilíbrio e força.', 'pernas', 'Apoie-se em uma perna e incline o tronco com a outra perna estendida atrás.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/stiff-unilateral.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Avanço (Passada) com Halteres', 'Exercício unilateral para pernas e glúteos.', 'pernas', 'Dê um passo à frente, desça o joelho traseiro e retorne à posição inicial.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/avanco-passada-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Avanço (Passada) com Barra', 'Avanço com barra nas costas.', 'pernas', 'Com a barra nas costas, dê passos à frente alternando as pernas.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/avanco-passada-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Avanço Caminhando', 'Avanço com deslocamento para frente.', 'pernas', 'Execute avanços caminhando para frente com halteres nas mãos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/avanco-caminhando.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Levantamento Terra Sumô', 'Levantamento terra com pernas afastadas.', 'pernas', 'Com os pés afastados e virados para fora, levante a barra do chão.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/levantamento-terra-sumo.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Levantamento Terra Romeno', 'Levantamento terra com foco em isquiotibiais.', 'pernas', 'Com pernas semi-estendidas, desça a barra até a canela e retorne.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/levantamento-terra-romeno.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Cadeira Adutora', 'Exercício para adutores na máquina.', 'pernas', 'Sentado na máquina, junte as pernas contra a resistência.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/cadeira-adutora.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Cadeira Abdutora', 'Exercício para abdutores na máquina.', 'pernas', 'Sentado na máquina, afaste as pernas contra a resistência.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/cadeira-abdutora.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Agachamento com Kettlebell', 'Agachamento segurando kettlebells.', 'pernas', 'Segure os kettlebells e agache mantendo o tronco ereto.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/agachamento-com-kettlebell.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Step Up com Halteres', 'Subida no banco com halteres.', 'pernas', 'Segurando halteres, suba em um banco alternando as pernas.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/step-up-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Agachamento Pistol', 'Agachamento completo com uma perna só.', 'pernas', 'Agache com uma perna só, a outra estendida à frente.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/agachamento-pistol.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Prensa de Pernas (Leg Press Vertical)', 'Leg press com plataforma vertical.', 'pernas', 'Deitado, empurre a plataforma vertical com os pés.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/prensa-de-pernas-leg-press-vertical.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Agachamento no Sissy Squat', 'Agachamento para isolamento do quadríceps.', 'pernas', 'Segure em um suporte, incline o corpo para trás e flexione os joelhos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/agachamento-no-sissy-squat.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Avanço Reverso', 'Avanço com passo para trás.', 'pernas', 'Dê um passo para trás, desça o joelho e retorne à posição inicial.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/avanco-reverso.gif', NULL, NOW(), NOW()),

-- ============================================================
-- GLÚTEOS (14 exercises)
-- ============================================================
(gen_random_uuid(), 'Hip Thrust com Barra', 'Exercício principal para glúteos.', 'glúteos', 'Apoie as costas no banco, posicione a barra no quadril e eleve o quadril.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/hip-thrust-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Hip Thrust na Máquina', 'Hip thrust guiado na máquina.', 'glúteos', 'Na máquina de hip thrust, eleve o quadril contra a resistência.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/hip-thrust-na-maquina.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Elevação Pélvica (Glute Bridge)', 'Ponte de glúteos no chão.', 'glúteos', 'Deitado de costas, eleve o quadril contraindo os glúteos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/elevacao-pelvica-glute-bridge.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Elevação Pélvica Unilateral', 'Ponte de glúteos com uma perna.', 'glúteos', 'Deitado, eleve o quadril com apenas uma perna apoiada no chão.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/elevacao-pelvica-unilateral.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Abdução de Quadril na Máquina', 'Abdução para glúteo médio na máquina.', 'glúteos', 'Sentado na máquina abdutora, abra as pernas contra a resistência.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/abducao-de-quadril-na-maquina.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Abdução de Quadril no Cabo', 'Abdução lateral usando cabo.', 'glúteos', 'Em pé, afaste a perna lateralmente contra a resistência do cabo.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/abducao-de-quadril-no-cabo.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Extensão de Quadril no Cabo', 'Extensão para glúteos no cabo.', 'glúteos', 'Em pé, estenda a perna para trás contra a resistência do cabo.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/extensao-de-quadril-no-cabo.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Kickback na Máquina (Glúteo)', 'Extensão de quadril na máquina.', 'glúteos', 'Na máquina, empurre a plataforma para trás com o pé.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/kickback-na-maquina-gluteo.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Agachamento Sumô com Halter', 'Agachamento sumô segurando halter para glúteos.', 'glúteos', 'Com pernas afastadas, agache segurando o halter entre as pernas.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/agachamento-sumo-com-halter.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Passada Lateral com Elástico', 'Caminhada lateral com elástico para glúteo médio.', 'glúteos', 'Com elástico nos tornozelos, caminhe lateralmente mantendo tensão.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/passada-lateral-com-elastico.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Coice de Glúteo (Donkey Kick)', 'Exercício no solo para glúteos.', 'glúteos', 'De quatro apoios, eleve a perna para trás mantendo o joelho flexionado.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/coice-de-gluteo-donkey-kick.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Fire Hydrant', 'Abdução de quadril no solo.', 'glúteos', 'De quatro apoios, abra a perna lateralmente mantendo o joelho flexionado.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/fire-hydrant.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Frog Pump', 'Elevação pélvica com joelhos abertos.', 'glúteos', 'Deitado com pés unidos e joelhos abertos, eleve o quadril.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/frog-pump.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Step Up Lateral', 'Subida lateral no banco para glúteo médio.', 'glúteos', 'Suba lateralmente no banco empurrando com a perna de apoio.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/step-up-lateral.gif', NULL, NOW(), NOW()),

-- ============================================================
-- ABDÔMEN (17 exercises)
-- ============================================================
(gen_random_uuid(), 'Prancha Frontal', 'Exercício isométrico para core.', 'abdômen', 'Apoie os antebraços e pontas dos pés no chão, mantenha o corpo reto.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/prancha-frontal.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Prancha Lateral', 'Isometria para oblíquos.', 'abdômen', 'Apoie-se em um antebraço lateralmente, mantendo o corpo alinhado.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/prancha-lateral.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Abdominal Crunch', 'Abdominal básico no solo.', 'abdômen', 'Deitado de costas, flexione o tronco contraindo o abdômen.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/abdominal-crunch.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Abdominal Crunch na Máquina', 'Abdominal na máquina com carga.', 'abdômen', 'Sentado na máquina, flexione o tronco contra a resistência.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/abdominal-crunch-na-maquina.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Abdominal Infra (Elevação de Pernas)', 'Exercício para abdômen inferior.', 'abdômen', 'Deitado, eleve as pernas estendidas até 90 graus e desça controladamente.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/abdominal-infra-elevacao-de-pernas.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Abdominal Bicicleta', 'Abdominal com rotação alternada.', 'abdômen', 'Deitado, toque o cotovelo no joelho oposto alternando os lados.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/abdominal-bicicleta.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Abdominal Oblíquo', 'Crunch lateral para oblíquos.', 'abdômen', 'Deitado de lado, flexione lateralmente contraindo os oblíquos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/abdominal-obliquo.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Elevação de Pernas na Barra Fixa', 'Abdominal avançado na barra.', 'abdômen', 'Pendurado na barra, eleve as pernas até a horizontal ou acima.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/elevacao-de-pernas-na-barra-fixa.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Elevação de Joelhos na Barra Fixa', 'Versão facilitada da elevação de pernas.', 'abdômen', 'Pendurado na barra, eleve os joelhos em direção ao peito.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/elevacao-de-joelhos-na-barra-fixa.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Abdominal na Roda (Ab Wheel)', 'Exercício avançado com roda abdominal.', 'abdômen', 'Ajoelhado, role a roda para frente e retorne contraindo o abdômen.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/abdominal-na-roda-ab-wheel.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Russian Twist', 'Rotação do tronco com peso.', 'abdômen', 'Sentado com tronco inclinado, rotacione o peso de lado a lado.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/russian-twist.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Mountain Climber', 'Exercício dinâmico para core.', 'abdômen', 'Em posição de prancha, alterne os joelhos em direção ao peito rapidamente.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/mountain-climber.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Dead Bug', 'Exercício de estabilização do core.', 'abdômen', 'Deitado de costas, estenda braço e perna opostos mantendo a lombar no chão.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/dead-bug.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Abdominal Canivete', 'Abdominal avançado com elevação simultânea.', 'abdômen', 'Deitado, eleve tronco e pernas simultaneamente tocando os pés.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/abdominal-canivete.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Prancha com Toque no Ombro', 'Prancha dinâmica com anti-rotação.', 'abdômen', 'Em posição de prancha alta, toque o ombro oposto alternando as mãos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/prancha-com-toque-no-ombro.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Pallof Press no Cabo', 'Exercício anti-rotação no cabo.', 'abdômen', 'Em pé lateral ao cabo, pressione o cabo à frente resistindo à rotação.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/pallof-press-no-cabo.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Prancha com Elevação de Perna', 'Prancha dinâmica com elevação alternada de pernas.', 'abdômen', 'Em posição de prancha, eleve uma perna de cada vez mantendo o core estável.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/prancha-com-elevacao-de-perna.gif', NULL, NOW(), NOW()),

-- ============================================================
-- PANTURRILHA (9 exercises)
-- ============================================================
(gen_random_uuid(), 'Panturrilha em Pé na Máquina', 'Exercício para gastrocnêmio.', 'panturrilha', 'Na máquina, eleve os calcanhares contraindo as panturrilhas.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/panturrilha-em-pe-na-maquina.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Panturrilha Sentado na Máquina', 'Exercício para sóleo.', 'panturrilha', 'Sentado na máquina, eleve os calcanhares contra a resistência.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/panturrilha-sentado-na-maquina.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Panturrilha no Leg Press', 'Panturrilha na plataforma do leg press.', 'panturrilha', 'No leg press, empurre a plataforma apenas com as pontas dos pés.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/panturrilha-no-leg-press.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Panturrilha no Smith', 'Panturrilha em pé no Smith com step.', 'panturrilha', 'No Smith com um step, eleve os calcanhares de forma controlada.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/panturrilha-no-smith.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Panturrilha com Halter', 'Panturrilha em pé com halteres.', 'panturrilha', 'Segurando halteres, eleve os calcanhares no chão ou em um step.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/panturrilha-com-halter.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Panturrilha Unilateral', 'Panturrilha com uma perna só.', 'panturrilha', 'Apoie-se em uma perna e eleve o calcanhar, segurando em um suporte.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/panturrilha-unilateral.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Panturrilha no Hack Squat', 'Panturrilha na máquina hack.', 'panturrilha', 'Na máquina hack, empurre a plataforma com as pontas dos pés.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/panturrilha-no-hack-squat.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Panturrilha com Peso Corporal (Escada)', 'Panturrilha em um degrau com peso corporal.', 'panturrilha', 'Em um degrau, desça os calcanhares e suba na ponta dos pés.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/panturrilha-com-peso-corporal-escada.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Panturrilha no Donkey Calf Raise', 'Panturrilha inclinado com carga nas costas.', 'panturrilha', 'Inclinado com carga nas costas, eleve os calcanhares.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/panturrilha-no-donkey-calf-raise.gif', NULL, NOW(), NOW()),

-- ============================================================
-- ANTEBRAÇO (8 exercises)
-- ============================================================
(gen_random_uuid(), 'Rosca de Punho com Barra', 'Flexão de punho para antebraço anterior.', 'antebraço', 'Apoie os antebraços no banco com as mãos para cima e flexione os punhos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-de-punho-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca de Punho Inversa com Barra', 'Extensão de punho para antebraço posterior.', 'antebraço', 'Apoie os antebraços com mãos para baixo e estenda os punhos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-de-punho-inversa-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca de Punho com Halter', 'Flexão de punho unilateral.', 'antebraço', 'Apoie o antebraço e flexione o punho com o halter.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-de-punho-com-halter.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Farmer Walk (Caminhada do Fazendeiro)', 'Exercício de pegada com deslocamento.', 'antebraço', 'Segure halteres pesados e caminhe mantendo postura ereta.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/farmer-walk-caminhada-do-fazendeiro.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Pegada no Halter (Dead Hang)', 'Sustentação na barra para força de pegada.', 'antebraço', 'Pendure-se na barra fixa pelo máximo de tempo possível.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/pegada-no-halter-dead-hang.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rosca Zottman', 'Rosca com rotação de punho.', 'antebraço', 'Suba com pegada supinada, rotacione no topo e desça com pegada pronada.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rosca-zottman.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Pronação e Supinação com Halter', 'Rotação do antebraço com halter.', 'antebraço', 'Segure o halter pela ponta e rotacione o antebraço para dentro e para fora.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/pronacao-e-supinacao-com-halter.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Roller de Punho (Wrist Roller)', 'Enrolamento de corda com peso.', 'antebraço', 'Segure o bastão com braços estendidos e enrole a corda levantando o peso.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/roller-de-punho-wrist-roller.gif', NULL, NOW(), NOW()),

-- ============================================================
-- TRAPÉZIO (10 exercises)
-- ============================================================
(gen_random_uuid(), 'Encolhimento com Halteres', 'Exercício básico para trapézio superior.', 'trapézio', 'Em pé, eleve os ombros em direção às orelhas com halteres nas mãos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/encolhimento-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Encolhimento com Barra', 'Encolhimento de ombros com barra.', 'trapézio', 'Segure a barra com braços estendidos e eleve os ombros.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/encolhimento-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Encolhimento na Máquina', 'Encolhimento guiado na máquina.', 'trapézio', 'Na máquina, eleve os ombros contra a resistência.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/encolhimento-na-maquina.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Encolhimento no Smith', 'Encolhimento de ombros no Smith.', 'trapézio', 'No Smith, eleve os ombros de forma controlada.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/encolhimento-no-smith.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Remada Alta com Barra (Trapézio)', 'Remada alta para trapézio superior.', 'trapézio', 'Puxe a barra verticalmente até a altura do queixo com cotovelos altos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/remada-alta-com-barra-trapezio.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Remada Alta com Halteres (Trapézio)', 'Remada alta com halteres para trapézio.', 'trapézio', 'Puxe os halteres verticalmente até o queixo.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/remada-alta-com-halteres-trapezio.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Face Pull (Trapézio Médio)', 'Face pull para trapézio médio e posterior.', 'trapézio', 'Puxe a corda do cabo alto em direção ao rosto separando as pontas.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/face-pull-trapezio-medio.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Y-T-W no Banco Inclinado', 'Exercício para trapézio médio e inferior.', 'trapézio', 'Deitado no banco inclinado, forme as letras Y, T e W com os braços.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/y-t-w-no-banco-inclinado.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Encolhimento com Kettlebell', 'Encolhimento usando kettlebells.', 'trapézio', 'Segure os kettlebells e eleve os ombros.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/encolhimento-com-kettlebell.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Farmer Walk com Trap Bar', 'Caminhada com trap bar para trapézio e pegada.', 'trapézio', 'Segure a trap bar carregada e caminhe mantendo postura ereta.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/farmer-walk-com-trap-bar.gif', NULL, NOW(), NOW()),

-- ============================================================
-- FUNCIONAL (21 exercises)
-- ============================================================
(gen_random_uuid(), 'Burpee', 'Exercício funcional de corpo inteiro.', 'funcional', 'Agache, apoie as mãos, salte para posição de prancha, flexão, salte para agachar e pule.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/burpee.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Kettlebell Swing', 'Balanço de kettlebell para cadeia posterior.', 'funcional', 'Segure o kettlebell entre as pernas e balance até a altura dos ombros usando o quadril.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/kettlebell-swing.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Turkish Get Up', 'Exercício funcional completo com kettlebell.', 'funcional', 'Deitado, levante-se mantendo o kettlebell estendido acima da cabeça.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/turkish-get-up.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Clean and Press com Barra', 'Levantamento olímpico simplificado.', 'funcional', 'Levante a barra do chão até os ombros e pressione acima da cabeça.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/clean-and-press-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Snatch com Kettlebell', 'Arranque com kettlebell.', 'funcional', 'Balance o kettlebell entre as pernas e lance acima da cabeça em um movimento.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/snatch-com-kettlebell.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Thruster com Barra', 'Agachamento frontal + desenvolvimento.', 'funcional', 'Agache com a barra na frente e ao subir pressione acima da cabeça.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/thruster-com-barra.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Thruster com Halteres', 'Agachamento + desenvolvimento com halteres.', 'funcional', 'Agache com halteres nos ombros e pressione ao subir.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/thruster-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Wall Ball', 'Agachamento com arremesso de bola na parede.', 'funcional', 'Agache segurando a medicine ball e arremesse na parede ao subir.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/wall-ball.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Box Jump', 'Salto sobre caixa pliométrica.', 'funcional', 'Salte sobre a caixa com ambos os pés e desça controladamente.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/box-jump.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Battle Rope (Corda Naval)', 'Exercício com cordas de batalha.', 'funcional', 'Segure as cordas e faça ondulações alternando os braços.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/battle-rope-corda-naval.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Sled Push (Trenó)', 'Empurrar o trenó para condicionamento.', 'funcional', 'Empurre o trenó carregado usando as pernas e o core.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/sled-push-treno.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Bear Crawl', 'Caminhada de urso para core e coordenação.', 'funcional', 'De quatro apoios com joelhos fora do chão, caminhe movendo mão e pé opostos.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/bear-crawl.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Medicine Ball Slam', 'Arremesso de medicine ball no chão.', 'funcional', 'Eleve a bola acima da cabeça e arremesse no chão com força.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/medicine-ball-slam.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Rowing (Remo Ergométrico)', 'Exercício cardiovascular e de força no remo.', 'funcional', 'No remo ergométrico, empurre com as pernas e puxe com os braços.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/rowing-remo-ergometrico.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Escalada na Corda (Rope Climb)', 'Subida na corda usando braços e pernas.', 'funcional', 'Suba a corda usando a técnica de prender com os pés e puxar com os braços.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/escalada-na-corda-rope-climb.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Salto em Profundidade (Depth Jump)', 'Salto pliométrico para potência.', 'funcional', 'Desça de uma caixa e imediatamente salte o mais alto possível ao tocar o chão.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/salto-em-profundidade-depth-jump.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Kettlebell Clean', 'Levantamento limpo com kettlebell.', 'funcional', 'Levante o kettlebell do chão até a posição de rack no ombro.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/kettlebell-clean.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Man Maker com Halteres', 'Combinação de flexão, remada, agachamento e desenvolvimento.', 'funcional', 'Flexão, remada alternada, salte para agachamento e pressione os halteres acima da cabeça.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/man-maker-com-halteres.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Pulo com Agachamento (Jump Squat)', 'Agachamento com salto para potência.', 'funcional', 'Agache e ao subir salte explosivamente, aterrisse suavemente.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/pulo-com-agachamento-jump-squat.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Swing com Halter', 'Balanço funcional com halter.', 'funcional', 'Segure o halter com ambas as mãos e balance usando o quadril.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/swing-com-halter.gif', NULL, NOW(), NOW()),
(gen_random_uuid(), 'Inchworm', 'Exercício funcional de deslocamento.', 'funcional', 'Em pé, caminhe com as mãos até a posição de prancha e caminhe os pés de volta.', 'https://coach-os.s3.us-east-1.amazonaws.com/exercises/global/inchworm.gif', NULL, NOW(), NOW());
