export const API_TAGS = {
  HEALTH: 'Health',
  AUTH: 'Auth',
  PERSONALS: 'Personals',
  EXERCISES: 'Exercises',
  WORKOUT_PLANS: 'Workout Plans',
  STUDENTS: 'Students',
  SERVICE_PLANS: 'Service Plans',
  AVAILABILITY: 'Availability',
  BOOKINGS: 'Bookings',
  PLANS: 'Plans',
  SUBSCRIPTIONS: 'Subscriptions',
  ADMIN: 'Admin',
  SUPPORT: 'Support',
};
